
drop table Person;

CREATE TABLE Person(
    id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name varchar(100) NOT NULL,
    age int check(age < 100)
);
select * from Person;


insert into Person(name, age) VALUES ('Tom', 48);
insert into Person(name, age) VALUES ('Nick', 18);
insert into Person(name, age) VALUES ('Katy', 35);


drop table Item;

CREATE TABLE Item(
    id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    person_id int REFERENCES Person (id) ON DELETE SET NULL,
    item_name varchar(150) NOT NULL
);
select * from Item;
select * from Person;

insert into Item(person_id, item_name) VALUES (1, 'Book');
insert into Item(person_id, item_name) VALUES (1, 'AirPods');
insert into Item(person_id, item_name) VALUES (2, 'Iphone');
insert into Item(person_id, item_name) VALUES (3, 'Kindle');
insert into Item(person_id, item_name) VALUES (3, 'TV');
insert into Item(person_id, item_name) VALUES (3, 'PlayStation');



drop table Passport;

CREATE TABLE Passport(
    id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    passport_number int NOT NULL,
    person_id int UNIQUE REFERENCES Person(id) ON DELETE CASCADE
);
select * from Passport;
select * from Person;

drop table Actor;

CREATE TABLE Actor(
   id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
   name varchar(100) NOT NULL,
   age int check(age > 0)
);

select * from Actor;

drop table Movie;

CREATE TABLE Movie(
    id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name varchar(100) NOT NULL,
    year_of_product int check(year_of_product >1900)
);

select * from Movie;

drop table Actor_Movie;
CREATE TABLE Actor_Movie(
    actor_id int REFERENCES Actor(id),
    movie_id int REFERENCES Movie(id),
    PRIMARY KEY (actor_id, movie_id)
);
select * from Actor_Movie;