CREATE TABLE Person(
  id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  username varchar(100) NOT NULL,
  year_of_birth int NOT NULL,
  password varchar NOT NULl,
  role varchar(100) NOT NULL
);



SELECT * FROM person;
DROP TABLE Person;

INSERT INTO Person (username, year_of_birth, "password", role) VALUES ('admin', 2000, 'admin', 'ROLE_ADMIN');
-- INSERT INTO Person (username, year_of_birth, "password", role) VALUES ('test_user2', 1980, 'test_password', 'ROLE_USER');

UPDATE Person set role='ROLE_ADMIN' where id=3;