
insert into Person(name, age, email) VALUES ('Tom', 48, 'tom@gmail.com');
insert into Person(name, age, email) VALUES ('Nick', 18, 'hick@gmail.com');
insert into Person(name, age, email) VALUES ('Katy', 35, 'katy@gmail.com');
insert into Person(name, age, email) VALUES ('Bob', 12, 'bob1@gmail.com');
insert into Person(name, age, email) VALUES ('Bob', 12, 'bob2@gmail.com');


CREATE TABLE Item(
    id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    person_id int REFERENCES Person (id) ON DELETE SET NULL,
    item_name varchar(150) NOT NULL
);
select * from Item;
select * from Person;

DROP table item;

insert into Item(person_id, item_name) VALUES (4, 'AirPods');
insert into Item(person_id, item_name) VALUES (4, 'TV');
insert into Item(person_id, item_name) VALUES (4, 'PlayStation');